const defaultTheme = {
  colHeaderHeight: 24,
  rowHeaderWidth: 40,
  colWidth: 120,
  rowHeight: 24,
  cellPadding: {
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 4,
    paddingBottom: 4,
  },
  default: {
    fillStyle: '#ffffff',
    strokeStyle: 'rgba(140,140,140,0.2)',
    protectedBackColor: 'rgba(140,140,140,0.1)',
    lineWidth: 1,
    textAlign: 'left',
    textBaseline: 'middle',
    wordWrap: false,
    lineHeight: 1.4,
    fontSize: 12,
    color: '#262626',
    fontFamily: 'Arial, sans-serif, "Microsoft YaHei"',
  },
  cellStyleDefault: {
    fontSize: 9,
    hAlign: 'left',
    vAlign: 'middle',
    fontWeight: 400,
    fontStyle: 'normal',
    underline: false,
    strikeThrough: false,
    color: '#262626',
    backColor: '#ffffff',
    overflow: 'overflow',
  },
  header: {
    fillStyle: '#fafafa',
    strokeStyle: '#c5c5c5',
    lineWidth: 1,
    textAlign: 'center',
    textBaseline: 'middle',
    font: '12px Arial, sans-serif, "Microsoft YaHei"',
    color: '#666',
  },
  activeHeader: {
    fillStyle: '#eff9ff',
    color: '#2a83ea',
  },
  freezeLine: {
    strokeStyle: '#4285f4',
    lineWidth: 2,
  },
}

export default defaultTheme
