const defaultTheme = {
  colHeaderHeight: 24,
  rowHeaderWidth: 40,
  colWidth: 120,
  rowHeight: 24,
  cellPadding: {
    left: 5,
    right: 5,
    top: 4,
    bottom: 4,
  },
  default: {
    fillStyle: '#ffffff',
    strokeStyle: 'rgba(140,140,140,0.3)',
    protectedBackColor: 'rgba(140,140,140,0.1)',
    lineWidth: 1,
    textAlign: 'left',
    textBaseline: 'middle',
    fontSize: 12,
    color: '#262626',
    fontFamily: 'Arial, sans-serif, "Microsoft YaHei"',
  },
  cellStyleDefault: {
    fontSize: 9,
    hAlign: 'left',
    vAlign: 'middle',
    fontWeight: 400,
    fontStyle: 'normal',
    underline: false,
    strikeThrough: false,
    color: '#262626',
    backColor: '#ffffff',
    overflow: 'overflow',
  },
  header: {
    fillStyle: '#fafafa',
    strokeStyle: 'rgba(120,120,120,0.3)',
    lineWidth: 1,
    textAlign: 'center',
    textBaseline: 'middle',
    font: '12px Arial, sans-serif, "Microsoft YaHei"',
    color: '#666',
  },
}

export default defaultTheme
